GestorDeTareas/Models/Entidades/Tarea.cs
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;

namespace GestorDeTareas.Models
{
    public partial class Tarea
    {
        internal static List<Tarea> ObtenerTareas(GestorDeTareasModelContainer db)
        {
            return db.TareaSet.Include(t => t.UsuarioAlta).Include(t => t.UsuarioAsignado).Include(t => t.Prioridad).Include(t => t.Estado).ToList();
        }

        internal static Tarea ObtenerTarea(GestorDeTareasModelContainer db, int? id)
        {
            return db.TareaSet.Include(t => t.UsuarioAlta).Include(t => t.UsuarioAsignado).Include(t => t.Prioridad).Include(t => t.Estado).FirstOrDefault(t => t.Id == id && t.FechaBaja == null);
        }

        internal static object ObtenerTareasVigentes(GestorDeTareasModelContainer db)
        {
            return db.TareaSet.Include(t => t.UsuarioAlta).Include(t => t.UsuarioAsignado).Include(t => t.Prioridad).Include(t => t.Estado).Where(t => t.FechaBaja == null).ToList();
        }

        internal static Tarea ObtenerTareaVigente(GestorDeTareasModelContainer db, int idTarea)
        {
            return db.TareaSet.FirstOrDefault(t => t.Id == idTarea && t.FechaBaja == null);
        }

        internal void ActualizarTareaEnDB(GestorDeTareasModelContainer db)
        {
            Tarea original = db.TareaSet.Find(Id);
            if (original != null) db.Entry(original).CurrentValues.SetValues(this);
        }
    }
}

GestorDeTareas/Models/Tarea.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GestorDeTareas.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tarea
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tarea()
        {
            this.Comentarios = new HashSet<Comentario>();
        }
    
        public int Id { get; set; }
        public string Titulo { get; set; }
        public string Descripcion { get; set; }
        public Nullable<int> UsuarioAsignadoId { get; set; }
        public Nullable<System.DateTime> FechaVencimiento { get; set; }
        public int UsuarioAltaId { get; set; }
        public System.DateTime FechaAlta { get; set; }
        public Nullable<int> UsuarioBajaId { get; set; }
        public Nullable<System.DateTime> FechaBaja { get; set; }
        public int PrioridadId { get; set; }
        public int EstadoId { get; set; }
    
        public virtual Usuario UsuarioAlta { get; set; }
        public virtual Usuario UsuarioAsignado { get; set; }
        public virtual Usuario UsuarioBaja { get; set; }
        public virtual Prioridad Prioridad { get; set; }
        public virtual Estado Estado { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Comentario> Comentarios { get; set; }
    }
}

GestorDeTareas/ViewModels/TareaViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Web.Mvc;

namespace GestorDeTareas.ViewModels
{
    public class TareaViewModel
    {
        public int? Id { get; set; }
        public int UsuarioAltaId { get; set; }
        public string NombreUsuAlta { get; set; }
        public string NombreUsuAsignado { get; set; }
        public string NombreEstado { get; set; }
        public string NombrePrioridad { get; set; }
        public DateTime FechaAlta { get; set; }

        [Display(Name = "Titulo")]
        [Required(ErrorMessage = "El título de la tarea no debe estar vacío")]
        public string Titulo { get; set; }

        [Display(Name = "Descripción")]
        [Required(ErrorMessage = "La descripción de la tarea no debe estar vacía")]
        public string Descripcion { get; set; }

        [Display(Name = "Asignado a:")]
        public int? UsuarioAsignado { get; set; }

        [Display(Name = "Vencimiento")]
        public DateTime? Vencimiento { get; set; }

        [Display(Name = "Prioridad")]
        public int Prioridad { get; set; }

        [Display(Name = "Nombre")]
        public int Estado { get; set; }

        //Drop down lists
        public List<SelectListItem> PrioridadesDDL { get; set; }
        public List<SelectListItem> EstadosDDL { get; set; }
        public List<SelectListItem> UsuariosDDL { get; set; }
    }
}

GestorDeTareas/Controllers/TareasController.cs
using GestorDeTareas.Models;
using GestorDeTareas.ViewModels;
using System;
using System.Data;
using System.Linq;
using System.Web.Mvc;

namespace GestorDeTareas.Controllers
{
    [CustomAuthorization]
    public class TareasController : BaseController
    {
        // GET: Tareas
        public ActionResult Index()
        {
            using (GestorDeTareasModelContainer db = new GestorDeTareasModelContainer()) return View(Tarea.ObtenerTareasVigentes(db));
        }

        // GET: Tareas/Create
        public ActionResult Alta()
        {
            return View(Cargarmodelo());
        }

        // POST: Tareas/Alta
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Alta(TareaViewModel modelo)
        {
            using (GestorDeTareasModelContainer db = new GestorDeTareasModelContainer())
            {
                if (ModelState.IsValid)
                {
                    db.TareaSet.Add(new Tarea
                    {
                        Titulo = modelo.Titulo,
                        Descripcion = modelo.Descripcion,
                        UsuarioAsignado = Usuario.ObtenerUsuarioPorId(db, modelo.UsuarioAsignado),
                        FechaVencimiento = modelo.Vencimiento,
                        UsuarioAlta = GetUsuarioLogueado(),
                        FechaAlta = DateTime.Now,
                        Prioridad = Prioridad.ObtenerPrioridad(db, modelo.Prioridad),  //TODO: Si viene null Baja, si no está Baja crearlo
                        Estado = Estado.ObtenerEstado(db, "Pendiente")  //TODO: Pendiente, si no está crearlo
                    });
                    db.SaveChanges();
                    return RedirectToAction("Index");
                }
            }
            //TODO: Informar Error
            return View(Cargarmodelo());
        }

        // GET: Tareas/Details/5
        public ActionResult Ver(int? id)
        {
            using (GestorDeTareasModelContainer db = new GestorDeTareasModelContainer())
            {
                Tarea tarea = Tarea.ObtenerTarea(db, id);
                if (tarea == null)
                {
                    //InformarError
                    return RedirectToAction("Index");
                }
                return View(tarea);
            }
        }

        // GET: Tareas/Edit/5
        public ActionResult Editar(int? id)
        {
            int idUsuarioLogueado = GetUsuarioLogueado().Id;
            using (GestorDeTareasModelContainer db = new GestorDeTareasModelContainer())
            {
                Tarea tarea = Tarea.ObtenerTarea(db, id);
                if (tarea == null || (tarea.UsuarioAltaId != idUsuarioLogueado && tarea.UsuarioAsignadoId != idUsuarioLogueado))
                {
                    //TODO: InformarError
                    return RedirectToAction("Index");
                }
                return View(CargarModelo(tarea));
            }
        }

        // POST: Tareas/Edit/5
        //[HttpPost]
        //[ValidateAntiForgeryToken]
        //public ActionResult Edit([Bind(Include = "Id,Titulo,Descripcion,UsuarioAsignadoId,FechaVencimiento,UsuarioAltaId,FechaAlta,UsuarioBajaId,FechaBaja,PrioridadId,EstadoId")] Tarea tarea)
        //{
        //    if (ModelState.IsValid)
        //    {
        //        db.Entry(tarea).State = EntityState.Modified;
        //        db.SaveChanges();
        //        return RedirectToAction("Index");
        //    }
        //    ViewBag.UsuarioAltaId = new SelectList(db.UsuarioSet, "Id", "Nombre", tarea.UsuarioAltaId);
        //    ViewBag.UsuarioAsignadoId = new SelectList(db.UsuarioSet, "Id", "Nombre", tarea.UsuarioAsignadoId);
        //    ViewBag.UsuarioBajaId = new SelectList(db.UsuarioSet, "Id", "Nombre", tarea.UsuarioBajaId);
        //    ViewBag.PrioridadId = new SelectList(db.PrioridadSet, "Id", "PrioridadDesc", tarea.PrioridadId);
        //    ViewBag.EstadoId = new SelectList(db.EstadoSet, "Id", "EstadoDesc", tarea.EstadoId);
        //    return View(tarea);
        //}

        //// GET: Tareas/Delete/5
        //public ActionResult Delete(int? id)
        //{
        //    if (id == null)
        //    {
        //        return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
        //    }
        //    Tarea tarea = db.TareaSet.Find(id);
        //    if (tarea == null)
        //    {
        //        return HttpNotFound();
        //    }
        //    return View(tarea);
        //}

        //// POST: Tareas/Delete/5
        //[HttpPost, ActionName("Delete")]
        //[ValidateAntiForgeryToken]
        //public ActionResult DeleteConfirmed(int id)
        //{
        //    Tarea tarea = db.TareaSet.Find(id);
        //    db.TareaSet.Remove(tarea);
        //    db.SaveChanges();
        //    return RedirectToAction("Index");
        //}

        [HttpPost]
        public JsonResult ActualizarVencimiento(int IdTarea, DateTime Fecha)
        {
            bool error = false;
            using (GestorDeTareasModelContainer db = new GestorDeTareasModelContainer())
            {
                Tarea tarea = Tarea.ObtenerTareaVigente(db, IdTarea);
                if (tarea != null && tarea.UsuarioAltaId == GetUsuarioLogueado().Id)
                {
                    tarea.FechaVencimiento = Fecha;
                    tarea.ActualizarTareaEnDB(db);
                    db.SaveChanges();
                }
                else
                {
                    error = true;
                }
            }
            return new JsonResult
            {
                Data = new
                {
                    success = true,
                    error
                },
                JsonRequestBehavior = JsonRequestBehavior.AllowGet
            };
        }

        [HttpPost]
        public JsonResult ActualizarPrioridad(int IdTarea, int IdPrioridad)
        {
            bool error = false;
            try
            {
                using (GestorDeTareasModelContainer db = new GestorDeTareasModelContainer())
                {
                    Tarea tarea = Tarea.ObtenerTareaVigente(db, IdTarea);
                    if (tarea != null && tarea.UsuarioAltaId == GetUsuarioLogueado().Id)
                    {
                        tarea.PrioridadId = IdPrioridad;
                        tarea.ActualizarTareaEnDB(db);
                        db.SaveChanges();
                    }
                    else
                    {
                        error = true;
                    }
                }
            }
            catch (Exception ex)
            {
                error = true;
            }
            return new JsonResult
            {
                Data = new
                {
                    success = true,
                    error
                },
                JsonRequestBehavior = JsonRequestBehavior.AllowGet
            };
        }

        private static TareaViewModel Cargarmodelo()
        {
            TareaViewModel modelo = new TareaViewModel();
            using (GestorDeTareasModelContainer db = new GestorDeTareasModelContainer())
            {
                modelo.EstadosDDL = Estado.ObtenerEstados(db).Select(u => new SelectListItem { Value = u.Id.ToString(), Text = u.EstadoDesc }).ToList();
                modelo.PrioridadesDDL = Prioridad.ObtenerPrioridades(db).Select(u => new SelectListItem { Value = u.Id.ToString(), Text = u.PrioridadDesc }).ToList();
            }
            return modelo;
        }

        private TareaViewModel CargarModelo(Tarea tarea)
        {
            TareaViewModel modelo = new TareaViewModel
            {
                Id = tarea.Id,
                Titulo = tarea.Titulo,
                Descripcion = tarea.Descripcion,
                UsuarioAsignado = tarea.UsuarioAsignadoId,
                UsuarioAltaId = tarea.UsuarioAltaId,
                Vencimiento = tarea.FechaVencimiento,
                NombreUsuAlta = tarea.UsuarioAlta.Nombre,
                NombreUsuAsignado = tarea.UsuarioAsignado?.Nombre,
                NombreEstado = tarea.Estado.EstadoDesc,
                NombrePrioridad = tarea.Prioridad.PrioridadDesc,
                FechaAlta = tarea.FechaAlta,
                Prioridad = tarea.PrioridadId,
                Estado = tarea.EstadoId
            };
            using (GestorDeTareasModelContainer db = new GestorDeTareasModelContainer())
            {
                modelo.EstadosDDL = Estado.ObtenerEstados(db).Select(u => new SelectListItem { Value = u.Id.ToString(), Text = u.EstadoDesc }).ToList();
                modelo.PrioridadesDDL = Prioridad.ObtenerPrioridades(db).Select(u => new SelectListItem { Value = u.Id.ToString(), Text = u.PrioridadDesc }).ToList();
                modelo.UsuariosDDL = Usuario.ObtenerUsuarios(db).Select(u => new SelectListItem { Value = u.Id.ToString(), Text = u.Nombre }).ToList();
            }
            return modelo;
        }
    }
}

GestorDeTareas/Views/Tareas/Alta.cshtml
@model GestorDeTareas.ViewModels.TareaViewModel

<h2>Nueva Tarea</h2>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Tarea</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Titulo, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Titulo, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Titulo, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Descripcion, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Descripcion, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Descripcion, "", new { @class = "text-danger" })
            </div>
        </div>

        @* TODO: Hacer un input, cargarlo y hacer la selección por ajax *@
        @*<div class="form-group">
            @Html.LabelFor(model => model.UsuarioAsignadoId, "UsuarioAsignadoId", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("UsuarioAsignadoId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.UsuarioAsignadoId, "", new { @class = "text-danger" })
            </div>
        </div>*@

        <div class="form-group">
            @Html.LabelFor(model => model.Vencimiento, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Vencimiento, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Vencimiento, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Prioridad, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(model => Model.Prioridad, Model.PrioridadesDDL, new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Prioridad, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Crear" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Volver a la lista", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

GestorDeTareas/Views/Tareas/Delete.cshtml
@model GestorDeTareas.Models.Tarea

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Tarea</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Titulo)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Titulo)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Descripcion)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Descripcion)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.FechaVencimiento)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FechaVencimiento)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.FechaAlta)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FechaAlta)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.FechaBaja)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FechaBaja)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.UsuarioAlta.Nombre)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.UsuarioAlta.Nombre)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.UsuarioAsignado.Nombre)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.UsuarioAsignado.Nombre)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.UsuarioBaja.Nombre)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.UsuarioBaja.Nombre)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Prioridad.PrioridadDesc)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Prioridad.PrioridadDesc)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Estado.EstadoDesc)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Estado.EstadoDesc)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

GestorDeTareas/Views/Tareas/Editar.cshtml
@using GestorDeTareas.Models
@model GestorDeTareas.ViewModels.TareaViewModel

@{
    ViewBag.Title = "Editar Tarea";
    Usuario usuarioLogueado = (Usuario)Session["user"];
}

<h2>Editar</h2>


<div class="form-horizontal">
    <h4>Tarea</h4>
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    @Html.HiddenFor(model => model.Id)

    <div class="form-group">
        @Html.LabelFor(model => model.Titulo, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.DisplayFor(model => model.Titulo)
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Descripcion, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.DisplayFor(model => model.Descripcion)
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.FechaAlta, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.DisplayFor(model => model.FechaAlta)
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Vencimiento, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @if (usuarioLogueado.Id == Model.UsuarioAltaId)
            {
                @Html.EditorFor(model => model.Vencimiento, new { htmlAttributes = new { @class = "form-control", Id = "dpVencimiento" } })
                @Html.ValidationMessageFor(model => model.Vencimiento, "", new { @class = "text-danger" })
            }
            else
            {
                @Html.DisplayFor(model => model.Vencimiento.Value.ToString("dd/MM/yyyy") ?? string.Empty)
            }
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.NombreUsuAlta, "UsuarioAltaId", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.DisplayFor(model => model.NombreUsuAlta)
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.UsuarioAsignado, new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.DisplayFor(model => model.NombreUsuAsignado)
            <input type="button" value="@(Model.UsuarioAsignado != null ? "Reasignar" : "Asignar")" class="btn btn-primary" id="btnAsignar">
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Prioridad, "PrioridadId", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @if (usuarioLogueado.Id == Model.UsuarioAltaId)
            {
                @Html.DropDownListFor(model => Model.Prioridad, Model.PrioridadesDDL, new { @class = "form-control", Id = "ddlPrioridad" })
                @Html.ValidationMessageFor(model => model.Prioridad, "", new { @class = "text-danger" })
            }
            else
            {
                @Html.DisplayFor(model => model.NombrePrioridad)
            }
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Estado, "EstadoId", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.DropDownListFor(model => Model.Estado, Model.EstadosDDL, new { @class = "form-control", Id = "ddlEstado" })
            @Html.ValidationMessageFor(model => model.Estado, "", new { @class = "text-danger" })
        </div>
    </div>
</div>

<div>
    @Html.ActionLink("Volver", "Index")
</div>

@section Styles {
    @Styles.Render("~/content/datepicker")
}

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
    @Scripts.Render("~/bundles/datepicker")
    <script>
        @if (usuarioLogueado.Id == Model.UsuarioAltaId)
        {
            <text>
                $("#dpVencimiento").datepicker({
                    format: "dd/mm/yyyy",
                    language: "es",
                    autoclose: true
                }).on("changeDate", function (e) {
                    $.ajax({
                        type: "POST",
                        url: '@Url.Action("ActualizarVencimiento", "Tareas")',
                        data: JSON.stringify({
                            IdTarea: @Model.Id,
                            Fecha: e.date
                        }),
                        contentType: "application/json; charset=utf-8",
                        dataType: "json",
                        success: function () {
                            //Informar OK
                        },
                        error: function () {
                            //Informar error y limpiar el campo
                        }
                    });
                });

                $("#ddlPrioridad").on("change", function () {
                    alert("Cambiando prioridad");
                });
            </text>
        }

        $("#ddlEstado").on("change", function () {
            alert("Cambiando estado");
        });

        $("#btnAsignar").on("click", function () {
            alert("Mostrar modal con la lista de usuarios");
        });
    </script>
}

GestorDeTareas/Views/Tareas/Index.cshtml
@model IEnumerable<GestorDeTareas.Models.Tarea>

<h2>Lista de tareas</h2>

<p>
    @Html.ActionLink("Nueva Tarea", "Alta")
</p>
<table class="table">
    <tr>
        <th>Título</th>
        <th>Descripción</th>
        <th>Fecha de Creación</th>
        <th>Fecha de Vencimiento</th>
        <th>Creado por</th>
        <th>Asignado a</th>
        <th>Prioridad</th>
        <th>Estado</th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Titulo)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Descripcion)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.FechaAlta)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.FechaVencimiento)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.FechaBaja)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.UsuarioAlta.Nombre)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.UsuarioAsignado.Nombre)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Prioridad.PrioridadDesc)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Estado.EstadoDesc)
        </td>
        <td>
            @Html.ActionLink("Ver Tarea", "Ver", new { id = item.Id }) |
            @Html.ActionLink("Eliminar", "Delete", new { id = item.Id })
        </td>
    </tr>
}

</table>

GestorDeTareas/Views/Tareas/Ver.cshtml
@using GestorDeTareas.Models
@model GestorDeTareas.Models.Tarea

@{
    ViewBag.Title = "Ver Tarea";
    Usuario usuarioLogueado = (Usuario)Session["user"];
}

<h2>Details</h2>

<div>
    <h4>Tarea</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>Título</dt>

        <dd>
            @Html.DisplayFor(model => model.Titulo)
        </dd>

        <dt>Descripción</dt>

        <dd>
            @Html.DisplayFor(model => model.Descripcion)
        </dd>

        <dt>Fecha de Creación</dt>

        <dd>
            @Html.DisplayFor(model => model.FechaAlta)
        </dd>

        <dt>Fecha de Vencimiento</dt>

        <dd>
            @Html.DisplayFor(model => model.FechaVencimiento)
        </dd>

        <dt>Creado por</dt>

        <dd>
            @Html.DisplayFor(model => model.UsuarioAlta.Nombre)
        </dd>

        <dt>Asignado a</dt>

        <dd>
            @Html.DisplayFor(model => model.UsuarioAsignado.Nombre)
        </dd>

        <dt>Prioridad</dt>

        <dd>
            @Html.DisplayFor(model => model.Prioridad.PrioridadDesc)
        </dd>

        <dt>Estado</dt>

        <dd>
            @Html.DisplayFor(model => model.Estado.EstadoDesc)
        </dd>

    </dl>
</div>
<p>
    @if (usuarioLogueado.Id == Model.UsuarioAlta.Id || usuarioLogueado.Id == Model.UsuarioAsignado?.Id)
    {
        @Html.ActionLink("Editar", "Editar", new { id = Model.Id });
    }
    @Html.ActionLink("Comentar", "Comentar")    @*TODO: Comentar por modal*@
    @Html.ActionLink("Volver", "Index")
</p>